<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AWSSDK.s3" Version="4.0.103.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetCoreS3Utility.Core\DotnetCoreS3Utility.Core.csproj" />
  </ItemGroup>

</Project>
